### ISSUE TITLE
Tray icon disappears when I try to hover mouse over it

### ISSUE THREAD

**Issue by saabismi** [PhantomGamers/SFP#135]
I think I managed to follow the installation instructions but when I open the SFP_UI.exe, there are SFP.log and SFP.config files appearing but the UI isn't opening (should it?). And when I go to the tray to look for the icon, it's there for a while but until I move my mouse towards it, the icon disappears.

My OS is Windows 8.1 and Steam version is the latest one available. I am wondering if the issue is related to my OS not being Windows 10 or 11 but let's hope that's not the case.

The log file looks like the following:

```
2023-06-22 12:49:41.3752|INFO|SFP.Models.Log|Initializing SFP version 0.0.47 on platform win81-x64
2023-06-22 12:49:41.6650|DEBUG|SFP.Models.Log|SelectedSkin is steamui.
2023-06-22 12:49:41.8465|INFO|SFP.Models.Log|Monitoring Steam state
2023-06-22 12:49:41.8465|ERROR|SFP.Models.Log|System.EntryPointNotFoundException: Unable to find an entry point named 'AdjustWindowRectExForDpi' in DLL 'user32.dll'.
   at FluentAvalonia.Interop.Win32Interop.AdjustWindowRectExForDpi(RECT* lpRect, Int32 dwStyle, BOOL bMenu, Int32 dwExStyle, Int32 dpi)
   at FluentAvalonia.UI.Windowing.Win32WindowManager.HandleNCCALCSIZE(WPARAM wParam, LPARAM lParam)
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProc(HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProcStatic(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by PhantomGamers** [comment]
Windows 10 is the minimum Windows version supported by Microsoft, and by the [FluentAvalonia](https://github.com/amwx/FluentAvalonia) library this app depends on.

If anyone would like to submit pull requests fixing issues on older operating systems I'd be happy to accept them, but I will not be providing support myself.

**Comment by kr0tchet** [comment]
As expected, SFP UI won't work with Windows 7 or 8.1, but SFP skinning itself will still work just fine.
