### ISSUE TITLE
SFP Crashes if kde.StatusNotifierWatcher service is not installed

### ISSUE THREAD

**Issue by Qwerty-Space** [PhantomGamers/SFP#137]
Error:
`2023-06-30 18:35:04.5036|ERROR|SFP.Models.Log|Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.StatusNotifierWatcher was not provided by any .service files`

**Comment by PhantomGamers** [comment]
Can you post the full SFP.log file? This error does not help me as I have no idea when it is happening

**Comment by MJ-asa** [comment]
I'm having the same problem, here is the full log

`2023-07-11 17:43:56.9524|INFO|SFP.Models.Log|Initializing SFP version 0.0.48 on platform endeavouros-x64
2023-07-11 17:43:57.2735|INFO|SFP.Models.Log|Monitoring Steam state
2023-07-11 17:43:57.2799|WARN|SFP.Models.Log|Steam is not running, cannot inject
2023-07-11 17:43:57.2799|INFO|SFP.Models.Log|Checking for updates...
2023-07-11 17:43:57.6112|INFO|SFP.Models.Log|You are running the latest version.
2023-07-11 17:44:04.0063|ERROR|SFP.Models.Log|Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.StatusNotifierWatcher was not provided by any .service files
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer)
   at Avalonia.FreeDesktop.DBusTrayIconImpl.CreateTrayIcon() in /_/src/Avalonia.FreeDesktop/DBusTrayIconImpl.cs:line 114
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 392
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 268
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 126
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 181
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 134
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 119
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 192
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at SFP_UI.Program.Main(String[]) in /home/runner/work/SFP/SFP/SFP_UI/Program.cs:line 43
`

**Comment by PhantomGamers** [comment]
Seems like this is already fixed upstream in Avalonia (https://github.com/AvaloniaUI/Avalonia/pull/11591), I'm just waiting for FluentAvalonia to get updated before I push a new release, which hopefully will happen at some point this week.

**Comment by PhantomGamers** [comment]
This should be fixed in https://github.com/PhantomGamers/SFP/releases/tag/0.0.49

If either of you can confirm that this is fixed I can close this :)

**Comment by MJ-asa** [comment]
Works perfectly so far! Thank you so much! ^w^
