### ISSUE TITLE
Multiple errors of the same kind

### ISSUE THREAD

**Issue by Potato95** [PhantomGamers/SFP#30]
[Warn] Could not delete C:\Users\user\AppData\Local\Steam\htmlcache\Cache\SFP\index which links to C:\Users\user\AppData\Local\Steam\htmlcache\Cache\index

[Error] System.UnauthorizedAccessException: Access to the path 'C:\Users\user\AppData\Local\Steam\htmlcache\Cache\SFP\index' is denied.

The error messages mention \SFP\index and \SFP\data_1 multiple times.

**Comment by PhantomGamers** [comment]
What operating system are you running? e.g. windows 10 or windows 11

If Windows 10, are you on the latest version of Windows 10?

Try running SFP as administrator and see if that fixes it

**Comment by Potato95** [comment]
Latest Win10 version, running as admin. Same error.

**Comment by GentlePuppet** [comment]
Can confirm on windows 10 pro 1909 I get the same errors.

`2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Found a entry https://community.akamai.steamstatic.com/public/css/webui/friends.css?v=IqXEoepFelo4&l=english with 2 addresses
2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Entry's Address 0 points to data_3
2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Entry's Address 1 points to f_000023
2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Found a entry https://community.cloudflare.steamstatic.com/public/css/webui/friends.css?v=IqXEoepFelo4&l=english&_cdn=cloudflare with 2 addresses
2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Entry's Address 0 points to data_2
2022-08-19 21:42:52.9767|DEBUG|SFP.Models.Log|Entry's Address 1 points to f_000004
2022-08-19 21:42:52.9827|WARN|SFP.Models.Log|Could not delete C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\SFP\index which links to C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\index
2022-08-19 21:42:52.9827|ERROR|SFP.Models.Log|System.UnauthorizedAccessException: Access to the path 'C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\SFP\index' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at SFP.Models.HardLink.RemoveHardLink(String filePath) in D:\a\SFP\SFP\SFP\Models\HardLink.cs:line 37
2022-08-19 21:42:52.9827|WARN|SFP.Models.Log|Could not delete C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\SFP\data_1 which links to C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\data_1
2022-08-19 21:42:52.9827|ERROR|SFP.Models.Log|System.UnauthorizedAccessException: Access to the path 'C:\Users\Wruzz\AppData\Local\Steam\htmlcache\Cache\SFP\data_1' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at SFP.Models.HardLink.RemoveHardLink(String filePath) in D:\a\SFP\SFP\SFP\Models\HardLink.cs:line 37`

**Comment by PhantomGamers** [comment]
It seems like this error is just saying that it couldn't delete the hardlink that it made, which I think should not otherwise impact functionality. Is SFP not functioning?

**Comment by Zacam** [comment]
Windows 10 Pro 22H2 (19045.2546)
Have set SFP_UI (0.0.14) to "Run as Administrator"
I've also set a "USERS" profile permissions for the "htmlcache" and sub-objects at "Full Control" in folder permissions

Still receive the same "Access to the path '...' is denied"; but it doesn't -appear- to be hindering any functionality

**Comment by RoseTheFlower** [comment]
Getting the same errors but yeah, still functioning.
