### ISSUE TITLE
Crash when resetting Steam files to stock under Linux

### ISSUE THREAD

**Issue by 62832** [PhantomGamers/SFP#59]
When attempting to revert all patches made to Steam, SFP throws the following stack trace before exiting as soon as the reset button is pressed.

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Gameloop.Vdf.Linq.VValue' to type 'System.Int32'.
   at SFP.Models.Steam.get_RunningGameID() in D:\a\SFP\SFP\SFP\Models\Steam.cs:line 23
   at SFP.Models.Steam.ResetSteam() in D:\a\SFP\SFP\SFP\Models\Steam.cs:line 146
   at SFP_UI.ViewModels.MainPageViewModel.OnResetSteamCommand() in D:\a\SFP\SFP\SFP_UI\ViewModels\MainPageViewModel.cs:line 187
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at SFP_UI.Program.Main(String[] args) in D:\a\SFP\SFP\SFP_UI\Program.cs:line 202023-01-07 12:05:10.2097|ERROR|SFP.Models.Log|System.InvalidCastException: Unable to cast object of type 'Gameloop.Vdf.Linq.VValue' to type 'System.Int32'.
   at SFP.Models.Steam.get_RunningGameID() in D:\a\SFP\SFP\SFP\Models\Steam.cs:line 23
   at SFP.Mod
els.Steam.ResetSteam() in D:\a\SFP\SFP\SFP\Models\Steam.cs:line 146
   at SFP_UI.ViewModels.MainPageViewModel.OnResetSteamCommand() in D:\a\SFP\SFP\SFP_UI\ViewModels\MainPageViewModel.cs:line 187
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at SFP_UI.Program.Main(String[] args) in D:\a\SFP\SFP\SFP_UI\Program.cs:line 20
```

In case this is part of the issue, I am running SFP under Artix Linux x64. If there's anything else I should clarify let me know.

**Comment by KawaiiSelbst** [comment]
Have you tried to do this with Steam enabled or not?

**Comment by PhantomGamers** [comment]
Sorry I forgot to respond to this but this is definitely an issue with the app, I'll fix this in the next update but I'm not sure when that'll be.
